
Activating Modules:
  1) defaultenv/10     2) lmod/7.5.13

[m8-17-14.rc.byu.edu:140072] mca: base: component_find: unable to open /apps/openmpi/1.10.7/gnu-4.8.5/lib/openmpi/mca_ess_pmi: libpmi.so.0: cannot open shared object file: No such file or directory (ignored)
[m8-17-14.rc.byu.edu:140072] mca: base: component_find: unable to open /apps/openmpi/1.10.7/gnu-4.8.5/lib/openmpi/mca_db_pmi: libpmi.so.0: cannot open shared object file: No such file or directory (ignored)
[m8-17-14.rc.byu.edu:140072] mca: base: component_find: unable to open /apps/openmpi/1.10.7/gnu-4.8.5/lib/openmpi/mca_grpcomm_pmi: libpmi.so.0: cannot open shared object file: No such file or directory (ignored)
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 65, in <module>
    import mpi4py
ModuleNotFoundError: No module named 'mpi4py'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 65, in <module>
    import mpi4py
ModuleNotFoundError: No module named 'mpi4py'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 65, in <module>
    import mpi4py
ModuleNotFoundError: No module named 'mpi4py'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 65, in <module>
    import mpi4py
ModuleNotFoundError: No module named 'mpi4py'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 65, in <module>
    import mpi4py
ModuleNotFoundError: No module named 'mpi4py'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 65, in <module>
    import mpi4py
ModuleNotFoundError: No module named 'mpi4py'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 65, in <module>
    import mpi4py
ModuleNotFoundError: No module named 'mpi4py'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 65, in <module>
    import mpi4py
ModuleNotFoundError: No module named 'mpi4py'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 65, in <module>
    import mpi4py
ModuleNotFoundError: No module named 'mpi4py'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 65, in <module>
    import mpi4py
ModuleNotFoundError: No module named 'mpi4py'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 65, in <module>
    import mpi4py
ModuleNotFoundError: No module named 'mpi4py'
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 65, in <module>
    import mpi4py
ModuleNotFoundError: No module named 'mpi4py'
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
Traceback (most recent call last):
  File "../../../src/mm_run.py", line 65, in <module>
    import mpi4py
ModuleNotFoundError: No module named 'mpi4py'
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[374,1],11]
  Exit code:    1
--------------------------------------------------------------------------
