
Activating Modules:
  1) defaultenv/10     2) lmod/7.5.13

[m9-25-3.rc.byu.edu:52834] mca: base: component_find: unable to open /apps/openmpi/1.10.7/gnu-4.8.5/lib/openmpi/mca_ess_pmi: libpmi.so.0: cannot open shared object file: No such file or directory (ignored)
[m9-25-3.rc.byu.edu:52834] mca: base: component_find: unable to open /apps/openmpi/1.10.7/gnu-4.8.5/lib/openmpi/mca_db_pmi: libpmi.so.0: cannot open shared object file: No such file or directory (ignored)
[m9-25-3.rc.byu.edu:52834] mca: base: component_find: unable to open /apps/openmpi/1.10.7/gnu-4.8.5/lib/openmpi/mca_grpcomm_pmi: libpmi.so.0: cannot open shared object file: No such file or directory (ignored)
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
Traceback (most recent call last):
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 25, in _import_mpi
    from mpi4py import MPI as _MPI
ModuleNotFoundError: No module named 'mpi4py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../src/mm_run.py", line 68, in <module>
    with MPIPool() as pool:
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 58, in __init__
    MPI = _import_mpi(use_dill=use_dill)
  File "/fslhome/djspenc/.local/lib/python3.8/site-packages/schwimmbad/mpi.py", line 33, in _import_mpi
    raise ImportError("Please install mpi4py")
ImportError: Please install mpi4py
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[51107,1],22]
  Exit code:    1
--------------------------------------------------------------------------
